bot:

    prefix:                         "trb "
    token:                          !ENV "BOT_TOKEN"

guild:
    
    id:                             403047405877985281
    
    categories:

        information:                455828584053866497
        chat:                       609926152731099145
        be_discussion:              403047405877985282
        cmp:                        629405848954732594
        smp:                        403103689356869634
        projects:                   645940131156459530
        staff:                      455833458439225347
        voice:                      403047405877985284

    roles:

        admin:      &ADMIN_ROLE     403101940034306048
        moderator:  &MOD_ROLE       455833793199079434
        helper:     &HELPER_ROLE    603138681280135178
        smp:                        403102052894638081
        cmp:                        623741560839864325
        trusted:    &TRUSTED_ROLE   403105260627034113
        mojang:                     646209238464462860
        everyone:                   403047405877985281
        muted:      &MUTED_ROLE     627614515483115527
        warned:     &WARNED_ROLE    617571086326038528

status:

    # Default server/alias to ping on blank status command
    # "all" will ping all aliases
    status_default:    "all"

    aliases:

        smp:                        "survival.techrock.org:19132"
        cmp:                        "creative.techrock.org:19132"

    ftp:     

        smp:

            ip:                     !ENV "FTP_SMP_IP"
            pt:                     21
            un:                     !ENV "FTP_SMP_UN"
            pw:                     !ENV "FTP_SMP_PW"

            userlist:               "/whitelist.json"

        cmp:

            ip:                     !ENV "FTP_CMP_IP"
            pt:                     21
            un:                     !ENV "FTP_CMP_UN"
            pw:                     !ENV "FTP_CMP_PW"

            userlist:               "/permissions.json"

config:

    required_keys: ['bot.token']